/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.distribuidos.servicorastreamento.cliente;
import com.distribuidos.servicorastreamento.erroMensagens.ErroMensagens;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;

/**
 *
 * @author joaoc
 */
public class ClienteInterface extends javax.swing.JFrame {

    private final Cliente cliente;
    /**
     * Creates new form ClienteInterface
     * @param cliente
     */
    
    public ClienteInterface(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanCliente = new javax.swing.JTabbedPane();
        panConsulta = new javax.swing.JPanel();
        txtCodigoRastreio = new javax.swing.JTextField();
        lblTxtCodigoRastreio = new javax.swing.JLabel();
        btnRastrearPacote = new javax.swing.JButton();
        panPacote = new javax.swing.JPanel();
        scrTblPacote = new javax.swing.JScrollPane();
        tblPacote = new javax.swing.JTable();
        lblCodigoPacote = new javax.swing.JLabel();
        cmbCodigoPacote = new javax.swing.JComboBox<>();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CLIENTE");

        txtCodigoRastreio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCodigoRastreio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoRastreioActionPerformed(evt);
            }
        });

        lblTxtCodigoRastreio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTxtCodigoRastreio.setText("Digite o código de rastreio abaixo:");

        btnRastrearPacote.setText("Rastrear Pedido");
        btnRastrearPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRastrearPacoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panConsultaLayout = new javax.swing.GroupLayout(panConsulta);
        panConsulta.setLayout(panConsultaLayout);
        panConsultaLayout.setHorizontalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTxtCodigoRastreio, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoRastreio, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRastrearPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        panConsultaLayout.setVerticalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblTxtCodigoRastreio)
                .addGap(30, 30, 30)
                .addComponent(txtCodigoRastreio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRastrearPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanCliente.addTab("Consultar pacotes", panConsulta);

        panPacote.setPreferredSize(new java.awt.Dimension(510, 242));

        tblPacote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Local", "Status", "Data e Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPacote.setColumnSelectionAllowed(true);
        tblPacote.getTableHeader().setReorderingAllowed(false);
        scrTblPacote.setViewportView(tblPacote);
        tblPacote.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblPacote.getColumnModel().getColumnCount() > 0) {
            tblPacote.getColumnModel().getColumn(0).setResizable(false);
            tblPacote.getColumnModel().getColumn(1).setResizable(false);
            tblPacote.getColumnModel().getColumn(2).setResizable(false);
        }

        lblCodigoPacote.setText("Código de rastreio:");

        cmbCodigoPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCodigoPacoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPacoteLayout = new javax.swing.GroupLayout(panPacote);
        panPacote.setLayout(panPacoteLayout);
        panPacoteLayout.setHorizontalGroup(
            panPacoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPacoteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPacoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrTblPacote, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(panPacoteLayout.createSequentialGroup()
                        .addComponent(lblCodigoPacote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbCodigoPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panPacoteLayout.setVerticalGroup(
            panPacoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPacoteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panPacoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigoPacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCodigoPacote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrTblPacote, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanCliente.addTab("Meus pacotes", panPacote);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPanCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoRastreioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoRastreioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoRastreioActionPerformed

    private void btnRastrearPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRastrearPacoteActionPerformed
        long codigoRastreio;        

        try
        {
            codigoRastreio = Long.valueOf(txtCodigoRastreio.getText());
            cliente.consultarCodigo(codigoRastreio);
        }
        catch (NumberFormatException ex)
        {
            String msg = "Número de rastreio vazio";
            Logger.getLogger(ClienteInterface.class.getName()).log(Level.SEVERE, msg, ex);
            ErroMensagens.avisoErro(msg);
        }
        
        txtCodigoRastreio.setText("");
    }//GEN-LAST:event_btnRastrearPacoteActionPerformed

    private void cmbCodigoPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCodigoPacoteActionPerformed
        String itemSelecionado = cmbCodigoPacote.getSelectedItem().toString(); 
        ArrayList<JSONObject> listaDePacotes = cliente.getListaDePacotes();
        DefaultTableModel model = (DefaultTableModel)tblPacote.getModel();
        
        model.setRowCount(0);
        
        Iterator<JSONObject> iterator = listaDePacotes.iterator();
        
        while (iterator.hasNext()) {
            JSONObject pacote = iterator.next();
            if(pacote.get("codigoRastreio").toString().equals(itemSelecionado))
                model.addRow(new Object[]
                {
                    pacote.get("origemPacote"),
                    "Cadastrado",
                    pacote.get("dataEnvio")
                });
        }
    }//GEN-LAST:event_cmbCodigoPacoteActionPerformed


    
    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        cliente.fecharCliente();
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    public void atualizarCombo(ArrayList<JSONObject> listaDePacotes){
        
        cmbCodigoPacote.removeAllItems();
        
        Iterator<JSONObject> iterator = listaDePacotes.iterator();
        
        while(iterator.hasNext()){
            JSONObject pacote = iterator.next();
            cmbCodigoPacote.addItem(pacote.get("codigoRastreio").toString());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRastrearPacote;
    private javax.swing.JComboBox<String> cmbCodigoPacote;
    private javax.swing.JLabel lblCodigoPacote;
    private javax.swing.JLabel lblTxtCodigoRastreio;
    private javax.swing.JPanel panConsulta;
    private javax.swing.JPanel panPacote;
    private javax.swing.JScrollPane scrTblPacote;
    private javax.swing.JTabbedPane tabPanCliente;
    private javax.swing.JTable tblPacote;
    private javax.swing.JTextField txtCodigoRastreio;
    // End of variables declaration//GEN-END:variables
}
