package com.distribuidos.servicorastreamento.servidor;

import com.distribuidos.servicorastreamento.erroMensagens.ErroMensagens;
import java.util.Date;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;


public class ServidorInterface extends javax.swing.JFrame {

    private final Servidor servidor;
    private float pesoPacote;
    private String origemPacote;
    private String destinoPacote;
    private JTable tabela; 

    public ServidorInterface(Servidor servidor) {
        this.servidor = servidor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        tabPanServidor = new javax.swing.JTabbedPane();
        panAdicionarPacote = new javax.swing.JPanel();
        lblTxtPesoPacote = new javax.swing.JLabel();
        txtPesoPacote = new javax.swing.JTextField();
        lblTxtOrigemPacote = new javax.swing.JLabel();
        txtOrigemPacote = new javax.swing.JTextField();
        lblTxtDestinoPacote = new javax.swing.JLabel();
        txtDestinoPacote = new javax.swing.JTextField();
        btnAdicionarPacote = new javax.swing.JButton();
        panConsultarPacotes = new javax.swing.JPanel();
        scrTblPacotes = new javax.swing.JScrollPane();
        tblPacotes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVIDOR");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblTxtPesoPacote.setText("Peso do pacote:");

        txtPesoPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoPacoteActionPerformed(evt);
            }
        });

        lblTxtOrigemPacote.setText("Origem:");

        txtOrigemPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigemPacoteActionPerformed(evt);
            }
        });

        lblTxtDestinoPacote.setText("Destino:");

        txtDestinoPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoPacoteActionPerformed(evt);
            }
        });

        btnAdicionarPacote.setText("Adicionar pacote");
        btnAdicionarPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPacoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAdicionarPacoteLayout = new javax.swing.GroupLayout(panAdicionarPacote);
        panAdicionarPacote.setLayout(panAdicionarPacoteLayout);
        panAdicionarPacoteLayout.setHorizontalGroup(
            panAdicionarPacoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdicionarPacoteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panAdicionarPacoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTxtOrigemPacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTxtDestinoPacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panAdicionarPacoteLayout.createSequentialGroup()
                        .addGroup(panAdicionarPacoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarPacote)
                            .addComponent(lblTxtPesoPacote)
                            .addComponent(txtDestinoPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrigemPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesoPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panAdicionarPacoteLayout.setVerticalGroup(
            panAdicionarPacoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdicionarPacoteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTxtPesoPacote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesoPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTxtOrigemPacote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOrigemPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTxtDestinoPacote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDestinoPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarPacote, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabPanServidor.addTab("Adicionar pacote", panAdicionarPacote);

        tblPacotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Postagem", "Peso", "Origem", "Destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPacotes.setColumnSelectionAllowed(true);
        tblPacotes.getTableHeader().setReorderingAllowed(false);
        scrTblPacotes.setViewportView(tblPacotes);
        tblPacotes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblPacotes.getColumnModel().getColumnCount() > 0) {
            tblPacotes.getColumnModel().getColumn(0).setResizable(false);
            tblPacotes.getColumnModel().getColumn(1).setResizable(false);
            tblPacotes.getColumnModel().getColumn(2).setResizable(false);
            tblPacotes.getColumnModel().getColumn(3).setResizable(false);
            tblPacotes.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout panConsultarPacotesLayout = new javax.swing.GroupLayout(panConsultarPacotes);
        panConsultarPacotes.setLayout(panConsultarPacotesLayout);
        panConsultarPacotesLayout.setHorizontalGroup(
            panConsultarPacotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsultarPacotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrTblPacotes, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        panConsultarPacotesLayout.setVerticalGroup(
            panConsultarPacotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultarPacotesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrTblPacotes, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanServidor.addTab("Consultar pacotes", panConsultarPacotes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFechar))
                    .addComponent(tabPanServidor))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabPanServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        servidor.fecharServidor();
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtOrigemPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigemPacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigemPacoteActionPerformed

    private void txtPesoPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoPacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoPacoteActionPerformed

    private void btnAdicionarPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPacoteActionPerformed
        boolean isValid;
        
        try
        {
            pesoPacote = Float.valueOf(txtPesoPacote.getText());
            origemPacote = txtOrigemPacote.getText().toUpperCase();
            destinoPacote = txtDestinoPacote.getText().toUpperCase();
            isValid = true;
        }
        catch(NumberFormatException ex)
        {
            Logger.getLogger(ServidorInterface.class.getName()).log(Level.SEVERE, "Erro ao cadastrar pacote", ex);
            isValid = false;
        }
        
        if(origemPacote.toString().equals("") || destinoPacote.toString().equals(""))
            isValid = false;
            
        
        txtPesoPacote.setText("");
        txtOrigemPacote.setText("");
        txtDestinoPacote.setText("");
        
        if(isValid){
            JSONObject pacote = new JSONObject();
        
            long codigoRastreio = (long)(new Random().nextDouble() * Math.pow(10, 10));

            pacote.put("dataEnvio", new Date().toString());
            pacote.put("codigoRastreio", codigoRastreio);
            pacote.put("pesoPacote", pesoPacote);
            pacote.put("origemPacote", origemPacote);
            pacote.put("destinoPacote", destinoPacote);

            servidor.addPacote(pacote);
        }
        else
        {
            ErroMensagens.avisoErro("As informações do pacote não são válidas");
        }
    }//GEN-LAST:event_btnAdicionarPacoteActionPerformed

    private void txtDestinoPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoPacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoPacoteActionPerformed

    public void atualizarTabela(ArrayList<JSONObject> listaDePacotes){
        DefaultTableModel model = (DefaultTableModel) tblPacotes.getModel();
        
        model.setRowCount(0);
        
        Iterator iterator = listaDePacotes.iterator();
        
        while(iterator.hasNext()){
            JSONObject pacote = (JSONObject)iterator.next();
            model.addRow(new Object[]
            {
                pacote.get("codigoRastreio"),
                pacote.get("dataEnvio"),
                pacote.get("pesoPacote"),
                pacote.get("origemPacote"),
                pacote.get("destinoPacote"),
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPacote;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel lblTxtDestinoPacote;
    private javax.swing.JLabel lblTxtOrigemPacote;
    private javax.swing.JLabel lblTxtPesoPacote;
    private javax.swing.JPanel panAdicionarPacote;
    private javax.swing.JPanel panConsultarPacotes;
    private javax.swing.JScrollPane scrTblPacotes;
    private javax.swing.JTabbedPane tabPanServidor;
    private javax.swing.JTable tblPacotes;
    private javax.swing.JTextField txtDestinoPacote;
    private javax.swing.JTextField txtOrigemPacote;
    private javax.swing.JTextField txtPesoPacote;
    // End of variables declaration//GEN-END:variables
}
